* prefixed all ENV variables  * fixed permissions (+x)  * some cs/debugging

diff --git a/phpfpm_average b/phpfpm_average
--- a/phpfpm_average
+++ b/phpfpm_average
@@ -15,23 +15,28 @@
 #%# family=manual
 #%# capabilities=autoconf
 
-PHP_BIN=${phpbin-"php5-fpm"}
+PHP_BIN=${munin_phpbin-"php5-fpm"}
+
+if [ ! -x "${PHP_BIN}" ]; then
+    echo "Not found or not executable: ${PHP_BIN}"
+    exit 1
+fi
 
 if [ "$1" = "autoconf" ]; then
-echo yes
-exit 0
+    echo yes
+    exit 0
 fi
 
 if [ "$1" = "config" ]; then
-echo 'graph_title PHP5-FPM Average Process Size'
-echo 'graph_args --base 1024 -l 0 '
-echo 'graph_vlabel PHP5-FPM Average Process Size'
-echo 'graph_category PHP'
-echo 'graph_info This graph shows the average process size for PHP5-FPM'
-echo 'php_average.label PHP5-FPM Average Proccess Size'
-echo 'php_average.draw LINE2'
-echo 'php_average.info The average process size for PHP5-FPM'
-exit 0
+    echo 'graph_title PHP5-FPM Average Process Size'
+    echo 'graph_args --base 1024 -l 0 '
+    echo 'graph_vlabel PHP5-FPM Average Process Size'
+    echo 'graph_category PHP'
+    echo 'graph_info This graph shows the average process size for PHP5-FPM'
+    echo 'php_average.label PHP5-FPM Average Proccess Size'
+    echo 'php_average.draw LINE2'
+    echo 'php_average.info The average process size for PHP5-FPM'
+    exit 0
 fi
 
 echo -n "php_average.value "
