* resolv full path and check executable

diff --git a/phpfpm_processes b/phpfpm_processes
--- a/phpfpm_processes
+++ b/phpfpm_processes
@@ -16,6 +16,12 @@
 #%# capabilities=autoconf
 
 PHP_BIN=${munin_phpbin-"php5-fpm"}
+PHP_BIN=$(which $PHP_BIN)
+
+if [ ! -x "${PHP_BIN}" ]; then
+    echo "Not found or not executable: ${PHP_BIN}"
+    exit 1
+fi
 
 if [ "$1" = "autoconf" ]; then
     echo yes
